# Sample .travis.yml for R projects

language: r
warnings_are_errors: true

env:
  - NOT_CRAN=true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      r: release
    - os: linux
      dist: trusty
      sudo: required
      r: devel
    - os: linux
      dist: trusty
      sudo: required
      r: oldrel
    - os: osx
      r: release

branches:
  only:
    - master
    - develop

after_success:
  - Rscript -e 'covr::codecov()'
