# Sample .travis.yml for R projects

language: r
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

env:
  - NOT_CRAN=true

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
  exclude:
    - os: osx
      r: devel
    - os: osx
      r: oldrel

branches:
  only:
    - master
    - develop

after_success:
  - Rscript -e 'covr::codecov()'
